nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*'] # Или замените на конкретные домены, если необходимо
        allow_headers: ['*']
        allow_methods: ['GET', 'OPTIONS', POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            max_age: 3600
